const express = require('express')
const authRoutes = require('./authRoutes')
const watchRoutes = require('./watchRoutes')
const cartRoutes = require('./cartRoutes')
const reviewRoutes = require('./reviewRoutes')
const wishlistRoutes = require('./wishlistRoutes')
const orderRoutes = require('./orderRoutes')
const categoryRoutes = require('./categoryRoutes')
const brandRoutes = require('./brandRoutes')
const couponRoutes = require('./couponRoutes')
const adminDashboardRoutes = require('./adminDashboardRoutes')
const userRoutes = require('./userRoutes')

const router = express.Router()

router.use('/auth', authRoutes)
router.use('/watches', watchRoutes)
router.use('/watches/:watchId/reviews', reviewRoutes)
router.use('/cart', cartRoutes)
router.use('/reviews', reviewRoutes)
router.use('/wishlist', wishlistRoutes)
router.use('/orders', orderRoutes)
router.use('/categories', categoryRoutes)
router.use('/brands', brandRoutes)
router.use('/coupons', couponRoutes)
router.use('/admin/dashboard', adminDashboardRoutes)
router.use('/admin', userRoutes)

module.exports = router
